name: dinner_generator_app
description: TDD and Clean architecture

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.7
  dio: ^4.0.4
  flutter_bloc: ^8.0.0
  bloc_test: ^9.0.1
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  hive_generator:
  build_runner: ^2.1.5


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


